name: CI

on: [push]

jobs:
  build-test:
    strategy:
      matrix:
        php: ['7.3', '7.4', '8.0', '8.1']

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v5
      with:
        php_version: ${{ matrix.php }}
    - uses: php-actions/phpunit@v3
      with:
        php_version: ${{ matrix.php }}
